const DATA_URL="./data/tou_data.xlsx",PERIODS=["경부하","중간부하","최대부하"],PERIOD_CLASS={"경부하":"off","중간부하":"mid","최대부하":"peak"},SEASONS=["하계","춘추계","동계"],DAY_TYPES=["평일","토요일","일·공휴일"];
const state={workbook:null,catalog:[],tariffs:[],schedules:[],usage:[],selectedCatalog:null,activeSeason:"하계",scenarioSchedule:null,scenarioDiscount:null,scenarioRates:null,lastResult:null};
const $=id=>document.getElementById(id),clone=o=>JSON.parse(JSON.stringify(o)),text=v=>String(v??"").trim(),number=v=>{const n=Number(String(v??"").replace(/,/g,""));return Number.isFinite(n)?n:0};
const normalizeDate=v=>{if(v instanceof Date)return v;const s=text(v).replace(/[^0-9]/g,"");return s.length===8?new Date(+s.slice(0,4),+s.slice(4,6)-1,+s.slice(6,8)):null},ymd=d=>d?`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}`:"-";
const fmtWon=n=>{const a=Math.abs(n),s=n<0?"-":"";if(a>=1e12)return s+(a/1e12).toLocaleString("ko-KR",{maximumFractionDigits:3})+"조원";if(a>=1e8)return s+(a/1e8).toLocaleString("ko-KR",{maximumFractionDigits:1})+"억원";if(a>=1e4)return s+(a/1e4).toLocaleString("ko-KR",{maximumFractionDigits:1})+"만원";return s+Math.round(a).toLocaleString("ko-KR")+"원"};
const fmtEnergy=n=>{const a=Math.abs(n),s=n<0?"-":"";if(a>=1e9)return s+(a/1e9).toLocaleString("ko-KR",{maximumFractionDigits:2})+"TWh";if(a>=1e6)return s+(a/1e6).toLocaleString("ko-KR",{maximumFractionDigits:2})+"GWh";if(a>=1e3)return s+(a/1e3).toLocaleString("ko-KR",{maximumFractionDigits:2})+"MWh";return s+a.toLocaleString("ko-KR",{maximumFractionDigits:1})+"kWh"};
const signedWon=n=>(n>=0?"+":"")+fmtWon(n),cssSign=n=>n>=0?"pos":"neg";
function sheetRows(wb,name){const ws=wb.Sheets[name];return ws?XLSX.utils.sheet_to_json(ws,{defval:"",raw:true}):[]}
async function loadGithubData(){setStatus("loading","GitHub 데이터 불러오는 중",DATA_URL);try{const res=await fetch(`${DATA_URL}?t=${Date.now()}`,{cache:"no-store"});if(!res.ok)throw new Error(`HTTP ${res.status}`);loadWorkbook(await res.arrayBuffer(),"GitHub")}catch(e){setStatus("error","GitHub 데이터 불러오기 실패",`${e.message} · Pages에서 실행 중인지, data/tou_data.xlsx가 있는지 확인`)}}
function loadWorkbook(buffer,source){try{if(typeof XLSX==="undefined")throw new Error("SheetJS 라이브러리를 불러오지 못함");const wb=XLSX.read(buffer,{type:"array",cellDates:true});state.workbook=wb;state.catalog=sheetRows(wb,"종별목록");state.tariffs=sheetRows(wb,"요금표");state.schedules=sheetRows(wb,"시간대기준");["종별목록","요금표","시간대기준"].forEach(n=>{if(!wb.Sheets[n])throw new Error(`필수 시트 '${n}' 없음`)});populateCategories();setStatus("ok",`${source} 데이터 연결 완료`,`${wb.SheetNames.length}개 시트 · ${new Date().toLocaleString("ko-KR")}`)}catch(e){setStatus("error","엑셀 구조 오류",e.message)}}
function setStatus(type,title,detail){$("dataStatus").className=`status ${type==="ok"?"ok":type==="error"?"error":""}`;$("dataStatus").textContent=title;$("dataDetail").textContent=detail}
function populateCategories(){const rows=state.catalog.filter(r=>text(r["활성화"]).toUpperCase()==="Y"&&state.workbook.Sheets[text(r["사용량시트명"])]);if(!rows.length)throw new Error("활성화된 종별 또는 사용량 시트가 없음");$("category").innerHTML=rows.map(r=>`<option value="${text(r["종별ID"])}">${text(r["표시명"])}</option>`).join("");selectCategory()}
function selectCategory(){const id=$("category").value||text(state.catalog[0]["종별ID"]);state.selectedCatalog=state.catalog.find(r=>text(r["종별ID"])===id);state.usage=parseUsage(sheetRows(state.workbook,text(state.selectedCatalog["사용량시트명"])));populateYears();populateTariffDimensions();populateVersions();loadScenarioPreset();updateWarning()}
function parseUsage(rows){return rows.map(r=>{const date=normalizeDate(r["날짜"]),year=number(r["연도"])||(date?date.getFullYear():0),month=number(r["월"])||(date?date.getMonth()+1:0),season=text(r["계절"]),dayType=text(r["요일"]||r["요일구분"]),hours=Array.from({length:24},(_,i)=>number(r[`H${String(i+1).padStart(2,"0")}`]));return{date,year,month,season,dayType,hours}}).filter(r=>r.date&&r.year&&SEASONS.includes(r.season)&&DAY_TYPES.includes(r.dayType))}
function populateYears(){const ys=[...new Set(state.usage.map(r=>r.year))].sort((a,b)=>b-a);$("year").innerHTML=ys.map(y=>`<option value="${y}">${y}년</option>`).join("")+(ys.length>1?`<option value="AVG">전체기간 연평균</option>`:"")}
function categoryTariffs(){return state.tariffs.filter(r=>text(r["요금그룹ID"])===text(state.selectedCatalog["요금그룹ID"]))}function categorySchedules(){return state.schedules.filter(r=>text(r["시간대그룹ID"])===text(state.selectedCatalog["시간대그룹ID"]))}function unique(rows,key){return[...new Set(rows.map(r=>text(r[key])).filter(Boolean))]}
function populateTariffDimensions(){$("contract").innerHTML=unique(categoryTariffs(),"계약전력구간").map(v=>`<option>${v}</option>`).join("");populateVoltage()}function populateVoltage(){const r=categoryTariffs().filter(x=>text(x["계약전력구간"])===$("contract").value);$("voltage").innerHTML=unique(r,"전압구분").map(v=>`<option>${v}</option>`).join("");populateChoice()}function populateChoice(){const r=categoryTariffs().filter(x=>text(x["계약전력구간"])===$("contract").value&&text(x["전압구분"])===$("voltage").value);$("choice").innerHTML=unique(r,"선택요금").map(v=>`<option>${v}</option>`).join("")}
function populateVersions(){const tr=categoryTariffs(),sr=categorySchedules(),ids=unique(tr,"버전ID").filter(id=>sr.some(r=>text(r["버전ID"])===id)),meta=id=>{const r=tr.find(x=>text(x["버전ID"])===id);return`${text(r["버전명"])} (${text(r["적용시작일"])}~${text(r["적용종료일"])})`},opts=ids.map(id=>`<option value="${id}">${meta(id)}</option>`).join("");$("baseVersion").innerHTML=opts;$("scenarioVersion").innerHTML=opts;if(ids.includes("PRE"))$("baseVersion").value="PRE";if(ids.includes("POST"))$("scenarioVersion").value="POST"}
function buildSchedule(versionId){const rows=categorySchedules().filter(r=>text(r["버전ID"])===versionId),schedule={},discount={};SEASONS.forEach(s=>{schedule[s]={};discount[s]={};DAY_TYPES.forEach(d=>{schedule[s][d]=Array(24).fill("경부하");discount[s][d]=Array(24).fill(1)})});rows.forEach(r=>{const s=text(r["계절"]),d=text(r["요일구분"]),h=number(r["시간"]);if(schedule[s]?.[d]&&h>=0&&h<24){schedule[s][d][h]=text(r["부하시간대"]);discount[s][d][h]=number(r["할인율"])||1}});return{schedule,discount}}
function buildRates(versionId){const rows=categoryTariffs().filter(r=>text(r["버전ID"])===versionId&&text(r["계약전력구간"])===$("contract").value&&text(r["전압구분"])===$("voltage").value&&text(r["선택요금"])===$("choice").value),rates={};SEASONS.forEach(s=>rates[s]={"경부하":0,"중간부하":0,"최대부하":0});rows.forEach(r=>{const s=text(r["계절"]),p=text(r["부하시간대"]);if(rates[s]&&PERIODS.includes(p))rates[s][p]=number(r["전력량요금"])});return rates}
function loadScenarioPreset(){const b=buildSchedule($("scenarioVersion").value);state.scenarioSchedule=clone(b.schedule);state.scenarioDiscount=clone(b.discount);state.scenarioRates=buildRates($("scenarioVersion").value);renderAll()}function copyBase(){const b=buildSchedule($("baseVersion").value);state.scenarioSchedule=clone(b.schedule);state.scenarioDiscount=clone(b.discount);state.scenarioRates=buildRates($("baseVersion").value);$("scenarioVersion").value=$("baseVersion").value;renderAll()}
function updateWarning(){const proxy=text(state.selectedCatalog["대리요금적용"]).toUpperCase()==="Y",dates=state.usage.map(r=>r.date).sort((a,b)=>a-b),period=dates.length?`${ymd(dates[0])}~${ymd(dates.at(-1))}`:"자료 없음";$("warning").innerHTML=proxy?`<b>환산 분석:</b> ${text(state.selectedCatalog["표시명"])} 부하에 ${text(state.selectedCatalog["요금그룹ID"])} 요금표를 대리 적용함. 사용량 자료기간 ${period}`:`<b>데이터 범위:</b> ${text(state.selectedCatalog["표시명"])} · ${period} · ${state.usage.length.toLocaleString()}일`}
function renderAll(){renderHours();renderScheduleCompare();renderRates();calculate()}function renderHours(){const d=$("dayType").value,a=state.scenarioSchedule?.[state.activeSeason]?.[d]||[];$("hourGrid").innerHTML=a.map((p,h)=>`<div class="hour ${PERIOD_CLASS[p]}" data-hour="${h}"><b>${String(h).padStart(2,"0")}~${String((h+1)%24).padStart(2,"0")}</b>${p}</div>`).join("");document.querySelectorAll(".hour").forEach(el=>el.onclick=()=>{const h=number(el.dataset.hour),c=state.scenarioSchedule[state.activeSeason][d][h];state.scenarioSchedule[state.activeSeason][d][h]=PERIODS[(PERIODS.indexOf(c)+1)%3];renderAll()})}
function renderScheduleCompare(){const d=$("dayType").value,b=buildSchedule($("baseVersion").value).schedule[state.activeSeason][d],s=state.scenarioSchedule[state.activeSeason][d];let h=`<div></div>${Array.from({length:24},(_,i)=>`<div class="muted" style="text-align:center">${i}</div>`).join("")}`;h+=`<div class="label">기준안</div>${b.map(p=>`<div class="mini ${PERIOD_CLASS[p]}">${p[0]}</div>`).join("")}`;h+=`<div class="label">시나리오</div>${s.map(p=>`<div class="mini ${PERIOD_CLASS[p]}">${p[0]}</div>`).join("")}`;$("scheduleCompare").innerHTML=h}
function rateTable(r,e){let h=`<thead><tr><th>계절</th>${PERIODS.map(p=>`<th>${p}</th>`).join("")}</tr></thead><tbody>`;SEASONS.forEach(s=>{h+=`<tr><td>${s==="춘추계"?"봄·가을철":s}</td>`;PERIODS.forEach(p=>h+=e?`<td><input type="number" step="0.1" data-season="${s}" data-period="${p}" value="${r[s][p].toFixed(1)}"></td>`:`<td>${r[s][p].toFixed(1)}</td>`);h+="</tr>"});return h+"</tbody>"}function renderRates(){$("baseRates").innerHTML=rateTable(buildRates($("baseVersion").value),false);$("scenarioRates").innerHTML=rateTable(state.scenarioRates,true);document.querySelectorAll("#scenarioRates input").forEach(i=>i.oninput=()=>{state.scenarioRates[i.dataset.season][i.dataset.period]=number(i.value);calculate()})}
function filteredUsage(){const y=$("year").value,s=$("scope").value,rows=state.usage.filter(r=>(y==="AVG"||r.year===number(y))&&(s==="연간"||r.season===s)),n=[...new Set(rows.map(r=>r.year))].length;return{rows,factor:y==="AVG"&&n?1/n:1}}
function calc(schedule,rates,discount,useDiscount){const{rows,factor}=filteredUsage(),bySeason={},byPeriod={};SEASONS.forEach(s=>bySeason[s]={usage:0,rev:0});PERIODS.forEach(p=>byPeriod[p]={usage:0,rev:0});let totalUsage=0,totalRev=0,days=0,minDate=null,maxDate=null,hourUsage=Array(24).fill(0);rows.forEach(r=>{days+=factor;if(!minDate||r.date<minDate)minDate=r.date;if(!maxDate||r.date>maxDate)maxDate=r.date;r.hours.forEach((raw,h)=>{const q=raw*factor,p=schedule[r.season][r.dayType][h],d=useDiscount?discount[r.season][r.dayType][h]:1,rev=q*rates[r.season][p]*d;totalUsage+=q;totalRev+=rev;hourUsage[h]+=q;bySeason[r.season].usage+=q;bySeason[r.season].rev+=rev;byPeriod[p].usage+=q;byPeriod[p].rev+=rev})});return{totalUsage,totalRev,days,minDate,maxDate,hourUsage,bySeason,byPeriod}}
function calculate(){if(!state.scenarioSchedule||!state.scenarioRates)return;const bb=buildSchedule($("baseVersion").value),br=buildRates($("baseVersion").value),base=calc(bb.schedule,br,bb.discount,true),sch=calc(state.scenarioSchedule,br,bb.discount,true),rat=calc(state.scenarioSchedule,state.scenarioRates,bb.discount,true),fin=calc(state.scenarioSchedule,state.scenarioRates,state.scenarioDiscount,$("useScenarioDiscount").checked),delta=fin.totalRev-base.totalRev;$("kUsage").textContent=fmtEnergy(fin.totalUsage);$("kPeriod").textContent=`${ymd(fin.minDate)}~${ymd(fin.maxDate)}`;$("kBase").textContent=fmtWon(base.totalRev);$("kScenario").textContent=fmtWon(fin.totalRev);$("kDelta").textContent=signedWon(delta);$("kDelta").className=cssSign(delta);$("kDeltaPct").textContent=base.totalRev?`${delta>=0?"+":""}${(delta/base.totalRev*100).toFixed(3)}%`:"-";$("kBaseAvg").textContent=base.totalUsage?(base.totalRev/base.totalUsage).toFixed(2):"-";$("kScenarioAvg").textContent=fin.totalUsage?(fin.totalRev/fin.totalUsage).toFixed(2):"-";const ds=sch.totalRev-base.totalRev,dr=rat.totalRev-sch.totalRev,dd=fin.totalRev-rat.totalRev;[["dSchedule",ds],["dRate",dr],["dDiscount",dd]].forEach(([id,v])=>{$(id).textContent=signedWon(v);$(id).className=cssSign(v)});renderSeasonTable(base,fin);renderPeriodTable(base,fin);renderChart(fin);state.lastResult={base,fin,ds,dr,dd}}
function renderSeasonTable(b,f){let h="<thead><tr><th>계절</th><th>기준안</th><th>시나리오</th><th>증감</th></tr></thead><tbody>";SEASONS.forEach(s=>{const d=f.bySeason[s].rev-b.bySeason[s].rev;h+=`<tr><td>${s==="춘추계"?"봄·가을철":s}</td><td>${fmtWon(b.bySeason[s].rev)}</td><td>${fmtWon(f.bySeason[s].rev)}</td><td class="${cssSign(d)}">${signedWon(d)}</td></tr>`});$("seasonTable").innerHTML=h+"</tbody>"}
function renderPeriodTable(b,f){let h="<thead><tr><th>시간대</th><th>기준 사용량</th><th>시나리오 사용량</th><th>변화</th></tr></thead><tbody>";PERIODS.forEach(p=>{const d=f.byPeriod[p].usage-b.byPeriod[p].usage;h+=`<tr><td>${p}</td><td>${fmtEnergy(b.byPeriod[p].usage)}</td><td>${fmtEnergy(f.byPeriod[p].usage)}</td><td class="${cssSign(d)}">${d>=0?"+":""}${fmtEnergy(d)}</td></tr>`});$("periodTable").innerHTML=h+"</tbody>"}
function renderChart(r){const svg=$("loadChart"),w=900,h=285,l=58,rr=18,t=36,b=35,vals=r.hourUsage.map(v=>r.days?v/r.days:0),max=Math.max(...vals,1)*1.08,x=i=>l+i*(w-l-rr)/23,y=v=>h-b-v/max*(h-t-b),day=$("dayType").value;let out="";for(let i=0;i<24;i++){const p=state.scenarioSchedule[state.activeSeason][day][i],xx=l+i*(w-l-rr)/24,ww=(w-l-rr)/24;out+=`<rect x="${xx}" y="3" width="${ww-1}" height="19" fill="var(--${PERIOD_CLASS[p]})"/><text x="${xx+ww/2}" y="16" text-anchor="middle" font-size="8">${p[0]}</text>`}for(let k=0;k<=4;k++){const yy=t+(h-t-b)*k/4;out+=`<line x1="${l}" y1="${yy}" x2="${w-rr}" y2="${yy}" stroke="#e4e8ed"/><text x="${l-7}" y="${yy+4}" text-anchor="end" font-size="9" fill="#687386">${((max*(4-k)/4)/1e6).toFixed(1)}</text>`}out+=`<text x="8" y="${t-7}" font-size="9" fill="#687386">백만 kWh/일</text><polyline points="${vals.map((v,i)=>`${x(i)},${y(v)}`).join(" ")}" fill="none" stroke="#2468ad" stroke-width="3"/>`;vals.forEach((v,i)=>{out+=`<circle cx="${x(i)}" cy="${y(v)}" r="2.3" fill="#2468ad"/>`;if(i%2===0)out+=`<text x="${x(i)}" y="${h-13}" text-anchor="middle" font-size="9" fill="#687386">${i}</text>`});svg.innerHTML=out}
function exportCsv(){const r=state.lastResult;if(!r)return;const rows=[["항목","값"],["종별",text(state.selectedCatalog["표시명"])],["연도",$("year").value],["범위",$("scope").value],["계약전력구간",$("contract").value],["전압구분",$("voltage").value],["선택요금",$("choice").value],["기준안 매출(원)",r.base.totalRev],["시나리오 매출(원)",r.fin.totalRev],["증감액(원)",r.fin.totalRev-r.base.totalRev],["시간대 효과(원)",r.ds],["단가 효과(원)",r.dr],["할인 효과(원)",r.dd],[],["계절","기준안(원)","시나리오(원)","증감(원)"]];SEASONS.forEach(s=>rows.push([s,r.base.bySeason[s].rev,r.fin.bySeason[s].rev,r.fin.bySeason[s].rev-r.base.bySeason[s].rev]));const csv="\ufeff"+rows.map(row=>row.map(v=>`"${String(v??"").replace(/"/g,'""')}"`).join(",")).join("\r\n"),blob=new Blob([csv],{type:"text/csv;charset=utf-8"}),a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download="TOU_매출_분석결과.csv";a.click();URL.revokeObjectURL(a.href)}
$("reloadData").onclick=loadGithubData;$("localFile").onchange=e=>{const f=e.target.files[0];if(!f)return;const reader=new FileReader();reader.onload=()=>loadWorkbook(reader.result,"PC 임시");reader.readAsArrayBuffer(f);e.target.value=""};$("category").onchange=selectCategory;$("contract").onchange=()=>{populateVoltage();populateVersions();loadScenarioPreset()};$("voltage").onchange=()=>{populateChoice();populateVersions();loadScenarioPreset()};$("choice").onchange=()=>{populateVersions();loadScenarioPreset()};$("baseVersion").onchange=renderAll;$("scenarioVersion").onchange=loadScenarioPreset;$("year").onchange=calculate;$("scope").onchange=calculate;$("dayType").onchange=renderAll;$("useScenarioDiscount").onchange=calculate;$("loadScenario").onclick=loadScenarioPreset;$("copyBase").onclick=copyBase;$("exportCsv").onclick=exportCsv;document.querySelectorAll("#seasonTabs .tab").forEach(btn=>btn.onclick=()=>{state.activeSeason=btn.dataset.season;document.querySelectorAll("#seasonTabs .tab").forEach(x=>x.classList.toggle("active",x===btn));renderAll()});document.querySelectorAll(".rate-adjust").forEach(btn=>btn.onclick=()=>{const m=number(btn.dataset.mult);SEASONS.forEach(s=>PERIODS.forEach(p=>state.scenarioRates[s][p]=Math.round(state.scenarioRates[s][p]*m*10)/10));renderAll()});loadGithubData();